### ISSUE TITLE
Flask support

### ISSUE THREAD

**Issue by sondrelg** [JonasKs/django-guid#35]
I haven't touched Flask in a while, but I suspect django-guid is compatible with Flask, either out of the box, or with some simple modifications. I suggest we investigate what it would take to integrate with Flask, and add Flask-setup-docs.

**Comment by ingvaldlorentzen** [comment]
I wonder if Flask support would maybe be better as  a fork that follows upstream closely?

**Comment by JonasKs** [comment]
Yeah, a fork would probably be the way to go. With ASGI becoming more and more popular I'm not sure how Flask will end up in the race either. I have no personal interest in Flask, but when #22 is solved I'd probably be up to look into porting it into Starlette or similar frameworks.

**Comment by JonasKs** [comment]
I’ll close this issue. Flask has signals so a fork and swap out Django logic is probably the way to go, but probably don’t belong in this package.
